@HospitalApi_HostAddress = http://localhost:5269

GET {{HospitalApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### Get all patients
GET {{HospitalApi_HostAddress}}/api/patients

### Search patients
GET {{HospitalApi_HostAddress}}/api/patients?search=ann
